{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 104857600,
      "rowLimit": 1000
     },
     "inputWidgets": {},
     "nuid": "a1f3b2ed-da94-4f32-8a05-6152b8538bff",
     "showTitle": false,
     "tableResultSettingsMap": {
      "0": {
       "dataGridStateBlob": "{\"version\":1,\"tableState\":{\"columnPinning\":{\"left\":[\"#row_number#\"],\"right\":[]},\"columnSizing\":{},\"columnVisibility\":{}},\"settings\":{\"columns\":{}},\"syncTimestamp\":1785868290296}",
       "filterBlob": null,
       "queryPlanFiltersBlob": null,
       "tableResultIndex": 0
      }
     },
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "WITH user_profiles AS (\n",
    "SELECT UserID,\n",
    "CASE\n",
    "WHEN Province=' ' THEN 'Uncategorized'\n",
    "WHEN Province='None' THEN 'Uncategorized'\n",
    "WHEN Province IS NULL THEN 'Uncategorized'\n",
    "ELSE Province\n",
    "END AS Region,\n",
    "age,\n",
    "CASE\n",
    "WHEN age = 0 THEN 'Infants'\n",
    "WHEN age BETWEEN 1 AND 12 THEN 'Kids'\n",
    "WHEN age BETWEEN 13 AND 19 THEN 'Teenager'\n",
    "WHEN age BETWEEN 20 AND 35 THEN 'Youth'WHEN age BETWEEN 36 AND 50 THEN 'Adult'\n",
    "WHEN age BETWEEN 51 AND 65 THEN 'Elder'\n",
    "WHEN age >65 THEN 'Pensioner'\n",
    "END AS age_groups,\n",
    "CASE\n",
    "WHEN Email IS NOT NULL OR Email=' ' OR Email NOT IN ('None')THEN 1\n",
    "ELSE 0\n",
    "END AS email_flag,\n",
    "CASE\n",
    "WHEN (`Social Media Handle` IS NOT NULL) OR (`Social Media Handle`=' ') OR (`Social Media Handle` NOT IN ('None')) THEN 1 \n",
    "        ELSE 0 \n",
    "    END AS sm_flag,\n",
    "CASE\n",
    "WHEN Race='other' THEN 'None'\n",
    "WHEN Race=' ' THEN 'None'\n",
    "ELSE Race\n",
    "END AS Race,\n",
    "CASE\n",
    "WHEN gender =' ' THEN 'None'\n",
    "ELSE gender\n",
    "END AS Gender\n",
    "FROM retail.default.userprofiles\n",
    "),\n",
    "viewership AS (\n",
    "SELECT\n",
    "COALESCE(UserID0,userid4) AS userid,\n",
    "TO_CHAR(RecordDate2, 'yyyyMM') AS month_id,\n",
    "TO_DATE(RecordDate2) AS watch_date,\n",
    "--TIME(RecordDate2) AS watch_time,\n",
    "TO_CHAR(RecordDate2, 'DD') AS day_of_week,\n",
    "DAYNAME(RecordDate2) AS day_name,\n",
    "CASE\n",
    "WHEN DAYNAME(RecordDate2) IN ('Sat', 'Sun') THEN 'weekend'\n",
    "ELSE 'weekday'\n",
    "END AS day_classification,\n",
    "MONTHNAME(RecordDate2) AS month_name,\n",
    "CASE\n",
    "WHEN Channel2 IN ('SawSee','Sawsee') THEN 'SawSee'\n",
    "WHEN Channel2 IN ('SuperSport Live Events','Live on SuperSport', 'Supersport Live Events',\n",
    "'DStv Events 1') THEN 'Live Events'\n",
    "ELSE Channel2\n",
    "END AS Tv_channel,DATE_FORMAT(RecordDate2, 'HH:mm:ss') AS watch_time,\n",
    "CASE\n",
    "WHEN HOUR(RecordDate2) BETWEEN 0 AND 5 THEN '01. Midnight'\n",
    "WHEN HOUR(RecordDate2) BETWEEN 6 AND 11 THEN '02. Morning'\n",
    "WHEN HOUR(RecordDate2) BETWEEN 12 AND 16 THEN '03. Afternoon'\n",
    "WHEN HOUR(RecordDate2) BETWEEN 17 AND 23 THEN '04. Evening'\n",
    "END AS time_of_day,\n",
    "DATE_FORMAT(`Duration 2`, 'HH:mm:ss') AS duration,\n",
    "CASE\n",
    "WHEN UNIX_TIMESTAMP(`Duration 2`) >= 300 AND UNIX_TIMESTAMP(`Duration 2`) <= 1800 THEN '01. Low Usage: <30 min'\n",
    "WHEN UNIX_TIMESTAMP(`Duration 2`) > 1800 AND UNIX_TIMESTAMP(`Duration 2`) <= 3599 THEN '02. Med Usage: <60 min'\n",
    "WHEN UNIX_TIMESTAMP(`Duration 2`) >= 3600 THEN '03. High Usage: >60 min'\n",
    "ELSE '04. No Usage'\n",
    "END AS screen_time_bucket,\n",
    "HOUR(RecordDate2) AS hour_of_day\n",
    "FROM retail.default.viewership\n",
    ")\n",
    "SELECT Coalesce(A.userid,B.userid) AS sub_id,\n",
    "month_id,\n",
    "watch_date,\n",
    "day_of_week,\n",
    "day_name,\n",
    "day_classification,month_name,\n",
    "Tv_channel,\n",
    "time_of_day,\n",
    "hour_of_day,\n",
    "screen_time_bucket,\n",
    "--user_flag,\n",
    "duration,\n",
    "Region,\n",
    "age_groups,\n",
    "email_flag,\n",
    "sm_flag,\n",
    "Race,\n",
    "Gender\n",
    "FROM viewership AS A\n",
    "LEFT JOIN user_profiles AS B\n",
    "ON A.userid=B.userid;\n",
    "SELECT\n",
    "    COALESCE(A.userid, B.userid) AS sub_id,\n",
    "    month_id,\n",
    "    watch_date,\n",
    "    day_in_dataset,\n",
    "    day_name,\n",
    "    day_classification,\n",
    "    month_name,\n",
    "    Tv_channel,\n",
    "    time_of_day,\n",
    "    hour_of_day,\n",
    "    screen_time_bucket,\n",
    "    duration,\n",
    "    Region,\n",
    "    age_groups,\n",
    "    email_flag,\n",
    "    sm_flag,\n",
    "    Race,\n",
    "    Gender\n",
    "\n",
    "FROM\n",
    "(\n",
    "    SELECT\n",
    "        COALESCE(UserID0, UserID4) AS userid,\n",
    "        TO_CHAR(RecordDate2, 'yyyyMM') AS month_id,\n",
    "        TO_DATE(RecordDate2) AS watch_date,\n",
    "        TO_CHAR(RecordDate2, 'DD') AS day_in_dataset,\n",
    "        DAYNAME(RecordDate2) AS day_name,\n",
    "        CASE\n",
    "            WHEN DAYNAME(RecordDate2) IN ('Sat','Sun') THEN 'weekend'\n",
    "            ELSE 'weekday'\n",
    "        END AS day_classification,\n",
    "        MONTHNAME(RecordDate2) AS month_name,\n",
    "        CASE\n",
    "            WHEN Channel2 IN ('SawSee','Sawsee') THEN 'SawSee'\n",
    "            WHEN Channel2 IN ('SuperSport Live Events',\n",
    "                              'Live on SuperSport',\n",
    "                              'Supersport Live Events',\n",
    "                              'DStv Events 1')\n",
    "            THEN 'Live Events'\n",
    "            ELSE Channel2\n",
    "        END AS Tv_channel,\n",
    "        DATE_FORMAT(RecordDate2,'HH:mm:ss') AS watch_time,\n",
    "        CASE\n",
    "            WHEN HOUR(RecordDate2) BETWEEN 0 AND 5 THEN '01. Midnight'\n",
    "            WHEN HOUR(RecordDate2) BETWEEN 6 AND 11 THEN '02. Morning'\n",
    "            WHEN HOUR(RecordDate2) BETWEEN 12 AND 16 THEN '03. Afternoon'\n",
    "            ELSE '04. Evening'\n",
    "        END AS time_of_day,\n",
    "        DATE_FORMAT(`Duration 2`,'HH:mm:ss') AS duration,\n",
    "        CASE\n",
    "            WHEN MINUTE(`Duration 2`) * 60 + SECOND(`Duration 2`) BETWEEN 300 AND 1800 THEN '01. Low Usage'\n",
    "            WHEN MINUTE(`Duration 2`) * 60 + SECOND(`Duration 2`) BETWEEN 1801 AND 3599 THEN '02. Med Usage'\n",
    "            WHEN MINUTE(`Duration 2`) * 60 + SECOND(`Duration 2`) >= 3600 THEN '03. High Usage'\n",
    "            ELSE '04. No Usage'\n",
    "        END AS screen_time_bucket,\n",
    "        HOUR(RecordDate2) AS hour_of_day\n",
    "    FROM retail.default.viewership\n",
    ") AS A\n",
    "\n",
    "LEFT JOIN\n",
    "\n",
    "(\n",
    "    SELECT\n",
    "        UserID,\n",
    "        CASE\n",
    "            WHEN Province=' ' THEN 'Uncategorized'\n",
    "            WHEN Province='None' THEN 'Uncategorized'\n",
    "            WHEN Province IS NULL THEN 'Uncategorized'\n",
    "            ELSE Province\n",
    "        END AS Region,\n",
    "\n",
    "        age,\n",
    "\n",
    "        CASE\n",
    "            WHEN age=0 THEN 'Infants'\n",
    "            WHEN age BETWEEN 1 AND 12 THEN 'Kids'\n",
    "            WHEN age BETWEEN 13 AND 19 THEN 'Teenager'\n",
    "            WHEN age BETWEEN 20 AND 35 THEN 'Youth'\n",
    "            WHEN age BETWEEN 36 AND 50 THEN 'Adult'\n",
    "            WHEN age BETWEEN 51 AND 65 THEN 'Elder'\n",
    "            WHEN age>65 THEN 'Pensioner'\n",
    "        END AS age_groups,\n",
    "\n",
    "        CASE\n",
    "            WHEN Email IS NOT NULL\n",
    "              OR Email=' '\n",
    "              OR Email NOT IN ('None')\n",
    "            THEN 1\n",
    "            ELSE 0\n",
    "        END AS email_flag,\n",
    "\n",
    "        CASE\n",
    "            WHEN `Social Media Handle` IS NOT NULL\n",
    "              OR `Social Media Handle`=' '\n",
    "              OR `Social Media Handle` NOT IN ('None')\n",
    "            THEN 1\n",
    "            ELSE 0\n",
    "        END AS sm_flag,\n",
    "\n",
    "        CASE\n",
    "            WHEN Race='other' THEN 'None'\n",
    "            WHEN Race=' ' THEN 'None'\n",
    "            ELSE Race\n",
    "        END AS Race,\n",
    "\n",
    "        CASE\n",
    "            WHEN Gender=' ' THEN 'None'\n",
    "            ELSE Gender\n",
    "        END AS Gender\n",
    "\n",
    "    FROM retail.default.userprofiles\n",
    ") AS B\n",
    "\n",
    "ON A.userid = B.userid;\n",
    "\n",
    "WITH user_profiles AS (\n",
    "SELECT UserID,\n",
    "CASE\n",
    "WHEN Province=' ' THEN 'Uncategorized'\n",
    "WHEN Province='None' THEN 'Uncategorized'\n",
    "WHEN Province IS NULL THEN 'Uncategorized'\n",
    "ELSE Province\n",
    "END AS Region,\n",
    "--------------------------------------------------------------------\n",
    "age,\n",
    "CASE\n",
    "WHEN age = 0 THEN 'Infants'\n",
    "WHEN age BETWEEN 1 AND 12 THEN 'Kids'\n",
    "WHEN age BETWEEN 13 AND 19 THEN 'Teenager'\n",
    "WHEN age BETWEEN 20 AND 35 THEN 'Youth'WHEN age BETWEEN 36 AND 50 THEN 'Adult'\n",
    "WHEN age BETWEEN 51 AND 65 THEN 'Elder'\n",
    "WHEN age >65 THEN 'Pensioner'\n",
    "END AS age_groups,\n",
    "CASE\n",
    "WHEN Email IS NOT NULL OR Email=' ' OR Email NOT IN ('None')THEN 1\n",
    "ELSE 0\n",
    "END AS email_flag,\n",
    "CASE\n",
    "WHEN (`Social Media Handle` IS NOT NULL) OR (`Social Media Handle`=' ') OR (`Social Media Handle` NOT IN ('None')) THEN 1 \n",
    "        ELSE 0 \n",
    "    END AS sm_flag,\n",
    "CASE\n",
    "WHEN Race='other' THEN 'None'\n",
    "WHEN Race=' ' THEN 'None'\n",
    "ELSE Race\n",
    "END AS Race,\n",
    "CASE\n",
    "WHEN gender =' ' THEN 'None'\n",
    "ELSE gender\n",
    "END AS Gender\n",
    "FROM retail.default.userprofiles\n",
    "),\n",
    "viewership AS (\n",
    "SELECT\n",
    "COALESCE(UserID0,userid4) AS userid,\n",
    "TO_CHAR(RecordDate2, 'yyyyMM') AS month_id,\n",
    "TO_DATE(RecordDate2) AS watch_date,\n",
    "--TIME(RecordDate2) AS watch_time,\n",
    "TO_CHAR(RecordDate2, 'DD') AS day_of_week,\n",
    "DAYNAME(RecordDate2) AS day_name,\n",
    "CASE\n",
    "WHEN DAYNAME(RecordDate2) IN ('Sat', 'Sun') THEN 'weekend'\n",
    "ELSE 'weekday'\n",
    "END AS day_classification,\n",
    "MONTHNAME(RecordDate2) AS month_name,\n",
    "CASE\n",
    "WHEN Channel2 IN ('SawSee','Sawsee') THEN 'SawSee'\n",
    "WHEN Channel2 IN ('SuperSport Live Events','Live on SuperSport', 'Supersport Live Events',\n",
    "'DStv Events 1') THEN 'Live Events'\n",
    "ELSE Channel2\n",
    "END AS Tv_channel,DATE_FORMAT(RecordDate2, 'HH:mm:ss') AS watch_time,\n",
    "CASE\n",
    "WHEN HOUR(RecordDate2) BETWEEN 0 AND 5 THEN '01. Midnight'\n",
    "WHEN HOUR(RecordDate2) BETWEEN 6 AND 11 THEN '02. Morning'\n",
    "WHEN HOUR(RecordDate2) BETWEEN 12 AND 16 THEN '03. Afternoon'\n",
    "WHEN HOUR(RecordDate2) BETWEEN 17 AND 23 THEN '04. Evening'\n",
    "END AS time_of_day,\n",
    "DATE_FORMAT(`Duration 2`, 'HH:mm:ss') AS duration,\n",
    "CASE\n",
    "WHEN UNIX_TIMESTAMP(`Duration 2`) >= 300 AND UNIX_TIMESTAMP(`Duration 2`) <= 1800 THEN '01. Low Usage: <30 min'\n",
    "WHEN UNIX_TIMESTAMP(`Duration 2`) > 1800 AND UNIX_TIMESTAMP(`Duration 2`) <= 3599 THEN '02. Med Usage: <60 min'\n",
    "WHEN UNIX_TIMESTAMP(`Duration 2`) >= 3600 THEN '03. High Usage: >60 min'\n",
    "ELSE '04. No Usage'\n",
    "END AS screen_time_bucket,\n",
    "HOUR(RecordDate2) AS hour_of_day\n",
    "FROM retail.default.viewership\n",
    ")\n",
    "SELECT Coalesce(A.userid,B.userid) AS sub_id,\n",
    "month_id,\n",
    "watch_date,\n",
    "day_of_week,\n",
    "day_name,\n",
    "day_classification,month_name,\n",
    "Tv_channel,\n",
    "time_of_day,\n",
    "hour_of_day,\n",
    "screen_time_bucket,\n",
    "--user_flag,\n",
    "duration,\n",
    "Region,\n",
    "age_groups,\n",
    "email_flag,\n",
    "sm_flag,\n",
    "Race,\n",
    "Gender\n",
    "FROM viewership AS A\n",
    "LEFT JOIN user_profiles AS B\n",
    "ON A.userid=B.userid;\n",
    "SELECT\n",
    "    COALESCE(A.userid, B.userid) AS sub_id,\n",
    "    month_id,\n",
    "    watch_date,\n",
    "    day_in_dataset,\n",
    "    day_name,\n",
    "    day_classification,\n",
    "    month_name,\n",
    "    Tv_channel,\n",
    "    time_of_day,\n",
    "    hour_of_day,\n",
    "    screen_time_bucket,\n",
    "    duration,\n",
    "    Region,\n",
    "    age_groups,\n",
    "    email_flag,\n",
    "    sm_flag,\n",
    "    Race,\n",
    "    Gender\n",
    "\n",
    "FROM\n",
    "(\n",
    "    SELECT\n",
    "        COALESCE(UserID0, UserID4) AS userid,\n",
    "        TO_CHAR(RecordDate2, 'yyyyMM') AS month_id,\n",
    "        TO_DATE(RecordDate2) AS watch_date,\n",
    "        TO_CHAR(RecordDate2, 'DD') AS day_in_dataset,\n",
    "        DAYNAME(RecordDate2) AS day_name,\n",
    "        CASE\n",
    "            WHEN DAYNAME(RecordDate2) IN ('Sat','Sun') THEN 'weekend'\n",
    "            ELSE 'weekday'\n",
    "        END AS day_classification,\n",
    "        MONTHNAME(RecordDate2) AS month_name,\n",
    "        CASE\n",
    "            WHEN Channel2 IN ('SawSee','Sawsee') THEN 'SawSee'\n",
    "            WHEN Channel2 IN ('SuperSport Live Events',\n",
    "                              'Live on SuperSport',\n",
    "                              'Supersport Live Events',\n",
    "                              'DStv Events 1')\n",
    "            THEN 'Live Events'\n",
    "            ELSE Channel2\n",
    "        END AS Tv_channel,\n",
    "        DATE_FORMAT(RecordDate2,'HH:mm:ss') AS watch_time,\n",
    "        CASE\n",
    "            WHEN HOUR(RecordDate2) BETWEEN 0 AND 5 THEN '01. Midnight'\n",
    "            WHEN HOUR(RecordDate2) BETWEEN 6 AND 11 THEN '02. Morning'\n",
    "            WHEN HOUR(RecordDate2) BETWEEN 12 AND 16 THEN '03. Afternoon'\n",
    "            ELSE '04. Evening'\n",
    "        END AS time_of_day,\n",
    "        DATE_FORMAT(`Duration 2`,'HH:mm:ss') AS duration,\n",
    "        CASE\n",
    "            WHEN MINUTE(`Duration 2`) * 60 + SECOND(`Duration 2`) BETWEEN 300 AND 1800 THEN '01. Low Usage'\n",
    "            WHEN MINUTE(`Duration 2`) * 60 + SECOND(`Duration 2`) BETWEEN 1801 AND 3599 THEN '02. Med Usage'\n",
    "            WHEN MINUTE(`Duration 2`) * 60 + SECOND(`Duration 2`) >= 3600 THEN '03. High Usage'\n",
    "            ELSE '04. No Usage'\n",
    "        END AS screen_time_bucket,\n",
    "        HOUR(RecordDate2) AS hour_of_day\n",
    "    FROM retail.default.viewership\n",
    ") AS A\n",
    "\n",
    "LEFT JOIN\n",
    "\n",
    "(\n",
    "    SELECT\n",
    "        UserID,\n",
    "        CASE\n",
    "            WHEN Province=' ' THEN 'Uncategorized'\n",
    "            WHEN Province='None' THEN 'Uncategorized'\n",
    "            WHEN Province IS NULL THEN 'Uncategorized'\n",
    "            ELSE Province\n",
    "        END AS Region,\n",
    "\n",
    "        age,\n",
    "\n",
    "        CASE\n",
    "            WHEN age=0 THEN 'Infants'\n",
    "            WHEN age BETWEEN 1 AND 12 THEN 'Kids'\n",
    "            WHEN age BETWEEN 13 AND 19 THEN 'Teenager'\n",
    "            WHEN age BETWEEN 20 AND 35 THEN 'Youth'\n",
    "            WHEN age BETWEEN 36 AND 50 THEN 'Adult'\n",
    "            WHEN age BETWEEN 51 AND 65 THEN 'Elder'\n",
    "            WHEN age>65 THEN 'Pensioner'\n",
    "        END AS age_groups,\n",
    "\n",
    "        CASE\n",
    "            WHEN Email IS NOT NULL\n",
    "              OR Email=' '\n",
    "              OR Email NOT IN ('None')\n",
    "            THEN 1\n",
    "            ELSE 0\n",
    "        END AS email_flag,\n",
    "\n",
    "        CASE\n",
    "            WHEN `Social Media Handle` IS NOT NULL\n",
    "              OR `Social Media Handle`=' '\n",
    "              OR `Social Media Handle` NOT IN ('None')\n",
    "            THEN 1\n",
    "            ELSE 0\n",
    "        END AS sm_flag,\n",
    "\n",
    "        CASE\n",
    "            WHEN Race='other' THEN 'None'\n",
    "            WHEN Race=' ' THEN 'None'\n",
    "            ELSE Race\n",
    "        END AS Race,\n",
    "\n",
    "        CASE\n",
    "            WHEN Gender=' ' THEN 'None'\n",
    "            ELSE Gender\n",
    "        END AS Gender\n",
    "\n",
    "    FROM retail.default.userprofiles\n",
    ") AS B\n",
    "\n",
    "ON A.userid = B.userid;"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": true,
     "catalog": "workspace",
     "schema": "default"
    }
   },
   "notebookName": "Bright Tv Big query.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
